name = "SECRET FILE"
author = "???"
start_background = "img/title.png"

[player]
starter = "start"
inventory = [
    "nothing",
]

[scene.lobby]
name = "Lobby"
background = "img/scene/lobby.png"

[scene.classroom]
name = "Classrom"
background = "img/scene/classroom.png"

[scene.final_stage]
name = "Final Stage"
background = "img/scene/final_stage.png"

[character.X]
name = "ZW5jb2Rl"
avatar = "img/character/X/X-avatar-normal.png"
avatar_happy = "img/character/X/X-avatar-happy.png"
avatar_sad = "img/character/X/X-avatar-sad.png"
tachie = "img/character/X/X-tachie-normal.png"
tachie_happy = "img/character/X/X-tachie-happy.png"
tachie_sad = "img/character/X/X-tachie-sad.png"

[character.Y]
name = "encode"
avatar = "img/character/Y/Y-avatar-normal.png"
avatar_happy = "img/character/Y/Y-avatar-happy.png"
avatar_sad = "img/character/Y/Y-avatar-sad.png"
tachie = "img/character/Y/Y-tachie-normal.png"
tachie_happy = "img/character/Y/Y-tachie-happy.png"
tachie_sad = "img/character/Y/Y-tachie-sad.png"

[character.Z]
name = "hash"
avatar = "img/character/Z/Z-avatar-normal.png"
avatar_happy = "img/character/Z/Z-avatar-happy.png"
avatar_sad = "img/character/Z/Z-avatar-sad.png"
tachie = "img/character/Z/Z-tachie-normal.png"
tachie_happy = "img/character/Z/Z-tachie-happy.png"
tachie_sad = "img/character/Z/Z-tachie-sad.png"


[item.nothing]
name = "bm90aGluZw=="
description = "SXQnIGp1c3Qgbm90aGluZy4="
icon = "img/item/nothing.png"

[item.base64]
name = "YmFzZTY0"
description = "5L2g6YCZ5YCLLi4u5bCB5byK6ICF"
icon = "img/item/base64.jpg"

[item.public_key]
name = "UHVibGljIEtleShlLG4p"
description = "(866215411, 2603700683)"
icon = "img/item/key.jpg"


[event.start]
scene = "lobby"
dialogue = "hello_world"

[event.know_ending]
end = "know"

[event.advance]
scene = "lobby"
dialogue = "ask_crypto_level"
item = "base64"

[event.beginer]
scene = "classroom"
dialogue = "tutorial_start"

[event.hash_tutorial]
scene = "classroom"
dialogue = "hash_tutorial"

[event.encrypt_tutorial]
scene = "classroom"
dialogue = "encrypt_only_tutorial"

[event.both_tutorial]
scene = "classroom"
dialogue = "encrypt_tutorial"

[event.rule_tutorial]
scene = "final_stage"
dialogue = "rule_description"

[event.choose_difficulty]
scene = "final_stage"
dialogue = "difficulty_select"

[event.normal_selection]
scene = "final_stage"
dialogue = "difficulty_normal"

[event.special_selection]
scene = "final_stage"
dialogue = "difficulty_select"
item = "public_key"

[event.warmup_end]
end = "warmup"

[event.baby_end]
end = "baby"

[dialogue.hello_world]
character = "X"
text = "5LuK5aSp5oiR6KaB5L6G5LuL57S55LiJ56iu5p2x6KW/"
[[dialogue.hello_world.options]]
text = "是什麼"
next = "ask_level"
favorability_add = +5
[[dialogue.hello_world.options]]
text = "哈哈，我已經知道了"
next = "already_know"
favorability_add = -100

[dialogue.already_know]
character = "X"
text = "ZmxhZyBmb3JtYXQ6IGZsYWd7fQ=="
[[dialogue.already_know.options]]
text = "我超電我一定解得出來"
event = "know_ending"

[dialogue.ask_level]
character = "X"
text = "5L2g55+l6YGT5oiR54++5Zyo6Kqq55qE5piv5LuA6bq85ZeO77yf"
[[dialogue.ask_level.options]]
text = "當然"
event = "advance"
favorability_add = +5
[[dialogue.ask_level.options]]
text = "............你說......什麼......"
event = "beginer"
favorability_add = +10

[dialogue.ask_crypto_level]
character = "X"
text = "5L2g55+l6YGTIGVuY3J5cHQg6LefIGhhc2gg5ZeO77yf"
[[dialogue.ask_crypto_level.options]]
text = "55+l6YGTIGVuY3J5cHQg6ICM5bey"
event = "hash_tutorial"
[[dialogue.ask_crypto_level.options]]
text = "55+l6YGTIGhhc2gg6ICM5bey"
event = "encrypt_tutorial"
[[dialogue.ask_crypto_level.options]]
text = "6YO95LiN55+l6YGT"
event = "both_tutorial"
[[dialogue.ask_crypto_level.options]]
text = "5oiR6YO955+l6YGT"
event = "rule_tutorial"

[dialogue.tutorial_start]
character = "X"
text = "現在我來介紹一下剛才說的是什麼，我剛才說話的都是用 base64 encode 的，而 encoding 是把資料轉成編碼，並沒有加密的效果"
[[dialogue.tutorial_start.options]]
text = "好"
next = "encrypt_tutorial"

[dialogue.encrypt_tutorial]
character = "Y"
text = "加密是把資料轉成另一種形式，使得別人無法直接看懂，而解密則是把加密後的資料轉回原本的形式，其中有對稱加密和非對稱加密兩種方式"
[[dialogue.encrypt_tutorial.options]]
text = "了解"
next = "hash_tutorial"
favorability_add = +10

[dialogue.hash_tutorial]
character = "Z"
text = "雜湊是把資料轉成固定長度的字串，而且不可逆，也就是無法從雜湊值回推原本的資料，常用於驗證資料的完整性"
[[dialogue.hash_tutorial.options]]
text = "了解"
event = "rule_tutorial"
favorability_add = +15

[dialogue.encrypt_only_tutorial]
character = "Y"
text = "加密是把資料轉成另一種形式，使得別人無法直接看懂，而解密則是把加密後的資料轉回原本的形式，其中有對稱加密和非對稱加密兩種方式"
[[dialogue.encrypt_only_tutorial.options]]
text = "了解"
event = "rule_tutorial"
favorability_add = +10

[dialogue.rule_description]
character = "X"
text = "接下來請找出一串ｆｌａｇ{}的文字"
[[dialogue.rule_description.options]]
text = "好"
event = "normal_selection"
favorability_add = -5
[[dialogue.rule_description.options]]
text = "CTF?"
event = "special_selection"
favorability_add = +100

[dialogue.difficulty_normal]
character = "X"
text = "請選擇難度"
[[dialogue.difficulty_normal.options]]
text = "warmup"
event = "warmup_end"

[dialogue.difficulty_select]
character = "X"
text = "請選擇難度"
[[dialogue.difficulty_select.options]]
text = "warm up"
event = "warmup_end"
[[dialogue.difficulty_select.options]]
text = "baby"
event = "baby_end"

[end.know]
title = "RkxBRyBmb3JtYXQ6IGZsYWd7fQ=="
background = "img/end/special.png"
text = "VlVoV2FXSkhiR3BKUlhSc1pWUnZaMHRFV1hkTmFsVXdUbnBKTUUxcVdYcE9lbFY1VGtScmQwMXFhM05KUkdNd1RucFJlazVFVlhwUFJFMTZUVlJSTkUxVVl6Sk9lbU53U1VWV2RWa3pTalZqU0ZKc1drUnZaMWQ2VFhwTmFsVjVUbXBWZUU1cVJYZE9ha2w2VFhwcmVFOVVSWE5KUkZWNVRtcEZOVTVxUVRGUFJFVjNUVVJOZDA1cVNUVk5ha0Z6U1VSUmQwNTZUVE5PUkVVd1RtcFJNRTVVUlRCT2Ftc3pUME4zWjAxVVkzcFBWR04zVFhwTmVFMVVaM2hPZWtrelRYcFpNMHhEUVRCUFZHTTFUWHBqZUU1NldUVk9SRlY1VFZSRk5FMTZTVE5NUTBFd1QwUmpNVTVxUVRCT1ZHTXdUMFJGTkUxVVFYZFBWR00wVEVOQmVFMXFUWGhPVkVVMVRYcHJlVTVFV1ROT2VsRjVUbXBKTTB4RFFYaE5SRmt5VGxScmVFNTZSWGhPVkZVd1RVUnJOVTlFU1hkTVEwRjRUVlJuTVU5RVNUSk5hbXN3VGtSTk0wNUVXVEJPVkdOM1RFTkJNMDFxU1RST1JHY3hUV3BuTlU1VVl6Rk9WR2N3VFdwSmVreERRWGhOYWsxM1RVUlZlVTFxYTNwT1JFa3hUMFJSTUU5RVl6Rk1RMEY0VFdwTmVFNVVSVFZOZW10NVRrUlpNMDU2VVhsT2Fra3pURU5CZWs1RVZUVk9la1Y0VFhwbk1rNUVRVEJPZWxWNVRucFZORXhEUVRKT2VsVXpUbnBaZVU5VVNURk5lbWN3VFhwTk5VMTZaM3BNUTBGNVRucEJNRTFxUVRGTlJGVXlUa1JuTlU1RVZYcE5WRUUxVEVOQmVFMXFUWGhPVkVVMVRYcHJlVTVFV1ROT2VsRjVUbXBKTTB4RFFUQk9WRWwzVG1wbk1FMVVRWGxOZW1ONVRYcEZORTVFUlhOSlJFVXdUV3BqZDA1RVJURk5lazB4VFhwSk1rNTZVVFZPUkVselNVUmplVTFxWnpCUFJGVjVUMFJyTVU1NlZURlBSRkY1VFdwTmMwbEVVWHBPUkUwd1QwUkZkMDU2YXpOUFZGazFUMVJuTlU1VVozTkpSRVY1VFhwRk1VMVVhM3BQVkVrd1RtcGpNMDVFU1RKTmFtTnpTVVJOZDA1VVJUTk9la1V5VGtSamQwNUVSVFZPZW1kNlRVUm5jMGxFV1hoT1JGRTBUbFJaZDAxRWEzaE5WRkV3VG1wVk1FOUVRWE5KUkUwelRtcFZNVTVxVFRSTmFrMHpUbFJGZDA1cVNUQk9SRlZ6U1VSTk1FNVVhek5OVkVWNlQwUlpNRTFFVVROT1ZFa3pUbFJuYzBsRVNYZE5SRmsxVFVSak1FMVVXVEJOUkdOM1RVUkJlRTVxUVhOSlJGVjRUVVJyTTA1cVZUQlBSRVUwVFhwWk1FNTZUWGhPYW10elNVUlJlVTVVWjNkTmVrazFUV3BWTUU1NlNUTk5WRVV3VDBSRmMwbEVSVEJOYW1OM1RrUkZNVTE2VFRGTmVra3lUbnBSTlU1RVNYTkpSRVY0VDBSVk5FMXFXWGxQVkZFd1RYcGpNRTVxVVRGT2VrRnpTVVJaZUU1RVVUUk9WRmwzVFVScmVFMVVVVEJPYWxVd1QwUkJjMGxFU1ROTlJHc3lUa1JSTlUxVVdUSk9SR3MxVDFSRmVFMTZhR1E9"
music = "music/Hack the World.mp3"

[end.warmup]
title = "Warm up"
background = "img/end/encode.jpg"
text = "Wm14aFozdmlyWkR3bjQ2RzhKK09pUENma3FiaW1wVHZ1STk5"
music = "music/Encoded Love.mp3"

[end.baby]
title = "YmFieSBSU0EgKG9yaWdpbiBmcm9tIEFJUzMp"
background = "img/end/encrypt.jpg"
text = "flag length:30 ; Encrypted: [1523290560, 750168374, 2601400693, 1652922160, 2503971748, 433705319, 433705319, 2179213890, 433705319, 433705319, 340433836, 1374569185, 340433836, 648083445, 1087059180, 582183200, 1275998069, 340433836, 604336931, 50368339, 648083445, 1626956101, 1356523296, 2385433874, 246170155, 340433836, 1626956101, 477919503, 1087059180, 2571358503]"
music = "music/Cryptic Love.mp3"